### ISSUE TITLE
data-model

### ISSUE THREAD

**Issue by williamking** [zhushh/TeamBuilder#1]
Add a diagram of data model.

**Comment by sptzxbbb** [comment]
**Move** data-model.md to wiki and **update** UML tool in it for cooperation.

**Comment by williamking** [comment]
I have done it. Any problem else? @sptzxbbb @KunMZ

**Comment by sptzxbbb** [comment]
- [x] Remove the data-model.md
- [x] Update UML tool in wiki for cooperation.
- [x] Keep the image and source file in **doc/img** folder as backup.

FYI, do this in dev branch until you're sure about it.
@williamking
