### ISSUE TITLE
Verification module

### ISSUE THREAD

**Issue by williamking** [zhushh/TeamBuilder#5]
编写用户邮件验证模块

**Comment by zhushh** [comment]
有发成功过了吗？

**Comment by williamking** [comment]
已经弄好了，注册成功时会发一封带验证链接的邮件，User的is_active字段会设为false，只有通过验证邮件的链接才能将is_active设为true。is_active表示User是否激活，控制其权限。

**Comment by zhushh** [comment]
OK
